### ISSUE TITLE
JSON config error

### ISSUE THREAD

**Issue by Lothar1994** [auchter/haaska#55]
I'm currently getting an error when running the "Alexa Smart Home - Discovery" test using the amazon lamda function.

The log out put shows: 
START RequestId: 5658d350-48bd-11e7-968a-cf0f4d9ff058 Version: $LATEST
[ERROR]	2017-06-04T00:32:49.897Z	5658d350-48bd-11e7-968a-cf0f4d9ff058	DiscoverAppliancesRequest failed
Traceback (most recent call last):
  File "/var/task/haaska.py", line 113, in handle_discover_appliances
    r['payload'] = {'discoveredAppliances': discover_appliances(ha)}
  File "/var/task/haaska.py", line 164, in discover_appliances
    states = ha.get('states')
  File "/var/task/haaska.py", line 55, in get
    return r.json()
  File "/var/task/requests/models.py", line 886, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decodedEND RequestId: 5658d350-48bd-11e7-968a-cf0f4d9ff058
REPORT RequestId: 5658d350-48bd-11e7-968a-cf0f4d9ff058	Duration: 580.27 ms	Billed Duration: 600 ms 	Memory Size: 128 MB	Max Memory Used: 32 MB

Would anyone know whats causing this? The only thing I've edited in the config file is the HA url (which I've set to my public ip address and port 8123) and the HA password - i know this is valid as I can access it via mobile and when changed the output log shows it cannot connect to the url.

Any help would be greatly appreciated!

**Comment by trisk** [comment]
The response is evidently malformed. Did you forget `/api` in the URL?

**Comment by Lothar1994** [comment]
yes you're right this was left out. But now I am getting i time out error:
{
  "errorMessage": "2017-06-04T05:49:56.938Z a18e0b77-48e9-11e7-a01d-8d8b7c8884de Task timed out after 3.00 seconds"
}
Am I missing something in Home assistant?

**Comment by trisk** [comment]
You need to increase your Lambda function's execution time limit.

**Comment by Lothar1994** [comment]
A reboot of my server running home assistant seemed to do the trick.
Thank you!
