### ISSUE TITLE
No devices discovered

### ISSUE THREAD

**Issue by radinsky** [auchter/haaska#80]
Hey, 

followed the installation guide both with video from Bruh.

I setup a skill and linked the account correct, but no devices could be discovered.
When running a test: 
```{
  "header": {
    "payloadVersion": "1",
    "namespace": "Control",
    "name": "DiscoverAppliancesRequest"
  },
  "payload": {
    "accessToken": "whatever"
  }
}
```

I'm getting:
```type object 'allowed' has no attribute 'Control': AttributeError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 660, in event_handler
    ha, payload)
  File "/var/task/haaska.py", line 289, in invoke
    obj = make_class(allowed)(namespace, name, ha, context)
AttributeError: type object 'allowed' has no attribute 'Control'
```

What could be wrong?

**Comment by radinsky** [comment]
Changed the lambda to US East (N. Virginia) and all devices found correctly and everything works ok (despite that i still getting errors on lambda test)
